<?php

namespace HETIC\CoreBundle\Repository;

/**
 * MatchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchesRepository extends \Doctrine\ORM\EntityRepository
{
}
